### PR TITLE
Initial commit

### PR DESCRIPTION
**Pull request by richjand**
Initial commit and push of epa/play blog

### CODE REVIEW

**Comment by mrcaseb** [comment]
Is this supposed to be merged @richjand or are you working on it?

**Comment by richjand** [comment]
Supposed to be merged

**Comment by mrcaseb** [comment]
Thanks for the post @richjand! Unfortunately this post is missing all meta files that are created by knitting the .Rmd file. Can you please knit the file and push all the resulting files?

I would also ask you to add the following code block to the end of your Rmd file. It creates a hyperlink to the source code 
https://github.com/nflverse/open-source-football/blob/6d7ecf276d17a648ea7eafb1842daa789fb8f7a9/_sample_meta_and_options.Rmd#L59-L75

**Comment by richjand** [comment]
Hope everything you need is there! Also thanks for hosting the site. It's a really nice public good and very much appreciated.

**Comment by mrcaseb** [comment]
Looks good to me, thanks!

**Pull request merged**
